### PR TITLE
one time check on Julia 1.6

### PR DESCRIPTION
**Pull request by visr**
Just want to double check if the builds are alright. No need to merge this, '1' will be '1.6' soon enough.

### CODE REVIEW

**Comment by visr** [comment]
So there seems to be an access violation in NetCDF.jl somewhere, that is only triggered on 1.6+. The build seems fine however, I just created https://github.com/Alexander-Barth/NCDatasets.jl/pull/123 to verify.

**Comment by meggart** [comment]
Thanks for checking this. I will try to get access to a windows computer and see if I can do something.

**Comment by visr** [comment]
With some print statements I managed to narrow it down to this line: https://github.com/JuliaGeo/NetCDF.jl/blob/8e25ee6e7ab19c0ca834f2b74c8c17014b54fb94/test/intermediate.jl#L78-L88

It doesn't seem to like that Dict that is set as an attribute. Don't really have time to dig deeper now though.

**Comment by Alexander-Barth** [comment]
For your information, in NCDatasets the `len` parameter has the type `Csize_t` to match the C-API: https://www.unidata.ucar.edu/software/netcdf/docs/group__attributes.html#ga14b66e0be82ccf41afe4c8f7f8b1f66a

NetCDF.jl (`len` is a signed `Cint`):
https://github.com/JuliaGeo/NetCDF.jl/blob/master/src/netcdf_c.jl#L727

NCDatasets.jl:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/netcdf_c.jl#L539

However, it is unlikely to be the issue here, because the failure seems to be specific to a julia version, but I wanted to let you know.

**Comment by meggart** [comment]
Thanks a lot for the hint @Alexander-Barth I think this might be the issue because the Julia 1.6 will pick up a different netcdf binary than other Julia versions. 

Any idea why all the `size_t` get translated to `Cint` by Clang.jl? Did you fix this manually or did you modify the wrap script?

**Comment by Alexander-Barth** [comment]
Glad to help :-) Actually, I change the file manually. But I was also surprised too about this type confusion: 

```
julia> Cint
Int32

julia> Csize_t
UInt64
```

**Comment by meggart** [comment]
So I just re-wrapped the netcdf header with a self-made wrapper, which does not rely on Clang and which preserves the original data types as "Csize_t". It looks like the windows tests are passing now, so I would clean the wrap script a bit and then add it to the repo in a new branch and PR.

**Comment by visr** [comment]
Failures were fixed in #141

**Pull request closed without merging**
