### PR TITLE
use the new NetCDF_jll; require julia 1.3

### PR DESCRIPTION
**Pull request by visr**
I wanted to give the new NetCDF_jll from JuliaPackaging/Yggdrasil#1090 a test run.

Since this relies on Artifacts being available it needs julia 1.3 minimum and therefore a minor version bump, to 0.11.

https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl

Also see https://github.com/Alexander-Barth/NCDatasets.jl/pull/88

### CODE REVIEW

**Comment by meggart** [comment]
Thanks a lot for trying this, indeed getting this fixed would be huge. I just returned from a longer break, but it looks like this https://github.com/JuliaPackaging/Yggdrasil/issues/1112 would need to get resolved first to make this PR work. I don't know how I could contribute right now....

**Comment by visr** [comment]
Welcome back! That is indeed the right issue.

Longer term we can hopefully fix https://github.com/JuliaPackaging/Yggdrasil/pull/567 but that will need work on the HDF5 build script, see also https://forum.hdfgroup.org/t/cross-compiling-for-windows/6735.

**Comment by musm** [comment]
I'm curious why HDF5.jl is holding this up?

**Comment by musm** [comment]
Is the exact HDF5 version important here? Apparently I've had two user report NetCDF is clashing with MATLAB.jl and I can't really do anything about it unfortunately.

**Comment by visr** [comment]
@musm there is more discussion here: https://github.com/Alexander-Barth/NCDatasets.jl/pull/88, about what is holding this up (`Warning! ***HDF5 library version mismatched error***`).

The exact HDF5 version is not important, what is important that the headers and binaries are mismatched right now.

**Comment by musm** [comment]
If anyone here wants to help with the hdf5 cross-compilation mission we need the output from https://github.com/musm/hdf5-build-output for various target systems

**Review by meggart — APPROVED** [review]
This is huge! Very good to see the Conda dependency go. Thank you.

**Pull request merged**
