### PR TITLE
add appveyor

### PR DESCRIPTION
**Pull request by visr**
Don't build NetCDF twice in Travis
Add .gitignore

### CODE REVIEW

**Comment by visr** [comment]
Shows it failing on 0.4 on Windows.
https://ci.appveyor.com/project/visr/netcdf-jl/build/1.0.3/job/qainarydegevinm1#L104

**Comment by meggart** [comment]
I will have a look, is this 32bit WIndows? Never tested this locally...

**Comment by visr** [comment]
It's also 64 bit. I have the same issue locally. I had a quick look but don't understand it yet, especially why it would be Windows only.

Perhaps an idea to regenerate `netcdf_c.jl` based on `Clang.jl` master? It has changed quite a lot, and I find it harder to read with the `@C` macro, which is no longer used. Don't know how many manual edits you did though.

**Comment by meggart** [comment]
This sounds like a good idea, I will be busy the next 2 days and have no WIndows machine, if you want to give it a try, feel free. Otherwise I will look into it in a few days.

**Comment by visr** [comment]
Sure I can give it a try. I'll let you know if I'm stuck.

**Pull request merged**
