### PR TITLE
Minor fixes on the intermediate.md doc

### PR DESCRIPTION
**Pull request by petershintech**

### CODE REVIEW

**Comment by petershintech** [comment]
I can see some documents surround variable names with backticks and others does with asterisks. Here, I used asterisks to be consistent with other parts in the same document. However, it might be better to use backticks consistently across all documents. The italic fonts with asterisks are not quite readable compared to backticks.

**Comment by visr** [comment]
Yeah, backticks around variable names is more commonly used and I think it makes sense since it refers to code. Would be great if you could update the whole document to backticks.

**Comment by petershintech** [comment]
@visr Ok, I will.

**Comment by petershintech** [comment]
Done

**Pull request merged**
