### PR TITLE
Revert "fix EXCEPTION_ACCESS_VIOLATION whilst reading strings"

### PR DESCRIPTION
**Pull request by visr**
This reverts commit b183f2c8f8140ca84c0db3cd017983ae23b70c11.

based on discusion here
https://github.com/JuliaGeo/NetCDF.jl/commit/b183f2c8f8140ca84c0db3cd017983ae23b70c11#commitcomment-22699065

### CODE REVIEW

**Comment by meggart** [comment]
Thanks, 

still, the access violation must have come from somewhere. I can imagine two situations:

1. If `nc_get_vara_string` does note succeed, the netcdf lib does not allocate the memory. However, this should immediately throw an error and `nc_free_string` should not be called. I don't know if there are cases where `nc_get_vara_string` fails but does not return an error
2. If you try to free more pointers than were actually allocated by the netcdf lib. This would happen, if the entries in `count` are less than the size of the returned array. So it would make sense to add a line `@assert prod(count)==length(retvalsa)`. This should prevent the access violation and give us some hint about when the bug would happen.

**Comment by visr** [comment]
Ok, it's a little hard to find out if I can't reproduce it though. And CI is happy as well.

**Comment by visr** [comment]
We could also initialize the vector of pointers to be all null pointers (`fill(Ptr{UInt8}(0), 5)`). Not sure if it would help, but feels safer than random pointers.

**Comment by meggart** [comment]
Good, I pushed these small changes on top of your branch, if the tests pass, we could merge from my side.

**Comment by visr** [comment]
Nice, thanks

**Pull request merged**
