### PR TITLE
Reformat the source code e.g. a space after comma

### PR DESCRIPTION
**Pull request by petershintech**
Formatted the source programs using formatting function in VC. Inserted
a space after a comma and give a space around an operator ... Overall,
the readability of the program code has been improved.

### CODE REVIEW

**Comment by visr** [comment]
Thanks, and sorry for the wait. Do you mind rebasing or just redoing it on current master?

**Comment by petershintech** [comment]
Sure. I will close this PR and send a new one.

**Comment by meggart** [comment]
Ok, let me know when it is there. I was about to fix your #96 but will wait for the reformatting first.

**Comment by petershintech** [comment]
Sorry for delay here,
I will reformat the code today.

**Pull request closed without merging**
